# Generated by Django 3.2.15 on 2022-09-17 09:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='BlogComment',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='BlogPost',
        ),
    ]
